platform :ios, ‘9.2’

use_frameworks!

def pods
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'SnapKit', '~> 0.22.0’
end
target ‘HQWB’ do
  pods
end
